import type { NextPage } from "next";
import Head from "next/head";

import Layout from "../components/Layout";
import Calender from "../components/Calender";
import { wrapper } from "../store";
import { Creators } from "../store/login";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Calender />
      </Layout>
    </>
  );
};

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (props) => {
    store.dispatch(Creators.loginSuccess({ isLogin: true, user: {} }));

    return {
      props: {},
    };
  }
);

export default Home;
